#!/bin/bash
npm install -D tailwindcss
npx tailwindcss init

cat > tailwind.config.js << _EOF_
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
_EOF_

mkdir src
cat > src/input.css << _EOF_ 
@tailwind base;
@tailwind components;
@tailwind utilities;
_EOF_

cat > src/index.html << _EOF_
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="/dist/output.css" rel="stylesheet">
</head>
<body>
  <h1 class="text-3xl text-blue-900 font-bold underline">
    Tailwind Letsgo by Neeraj Adhav
  </h1>
</body>
</html>
_EOF_

npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch
